# Site settings
title: Aaron Bruce
email: aaronbruce555@gmail.com
description: Trained by App Academy and self-taught software developer with experience working on Full Stack Apps in Javascript, React, Node, Express, postgreSQL, & MongoDB
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://aaronthebruce.github.io/" # the base hostname & protocol for your site

linkedin_username: aaronbruce555
github_username: AaronTheBruce

# Build settings
markdown: kramdown
